name: Code Quality Check

on: [push]

jobs:
  build:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i
        working-directory: ./frontend


      - name: Set up .npmrc
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./frontend


      - name: Test
        run: test-script --test-token=${{ secrets.TEST_PROJECT_TOKEN }}
        working-directory: ./frontend

      - name: Run Unit Tests
        run: npm run test
        working-directory: ./frontend
