name: Code Quality Check

on: [push]

jobs:
  build:
    name: Code Quality Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.2]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up .npmrc
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
    

      - name: Install Node Modules
        run: npm install

      - name: Run Unit Tests
        run: npm run test
